/*
 * @auth Francesco Baldi
 * @class bld.commons.service.JpaService.java
 */
package com.bld.commons.service;

import java.util.Collection;
import java.util.List;
import java.util.Map;

import com.bld.commons.reflection.model.NativeQueryParameter;
import com.bld.commons.reflection.model.QueryParameter;
import com.bld.commons.utils.JpaRowMapper;
import com.bld.commons.utils.PersistenceMap;


/**
 * Generic service interface for JPA-managed entities.
 *
 * <p>Provides a complete set of CRUD operations plus dynamic query execution
 * capabilities through {@link QueryParameter} and {@link NativeQueryParameter}.
 * All filter-based methods build JPQL or native SQL queries at runtime by
 * inspecting the parameter object via reflection.</p>
 *
 * <h3>Basic usage</h3>
 * <pre>{@code
 * // Simple CRUD
 * myService.save(entity);
 * MyEntity found = myService.findById(42L);
 * myService.delete(found);
 *
 * // Dynamic filter query
 * QueryParameter<MyEntity, Long> qp = new QueryParameter<>(new MyFilter());
 * List<MyEntity> results = myService.findByFilter(qp);
 * }</pre>
 *
 * @param <T>  the entity type managed by this service
 * @param <ID> the type of the entity's primary key
 * @author Francesco Baldi
 * @see JpaServiceImpl
 * @see QueryParameter
 * @see NativeQueryParameter
 */
public interface JpaService<T, ID> {

	/**
	 * Returns the total number of entities of type {@code T} in the database.
	 *
	 * @return total entity count
	 */
	public abstract long count();

	/**
	 * Deletes the given entity.
	 *
	 * @param entity the entity to delete; must not be {@code null}
	 */
	public abstract void delete(T entity);

	/**
	 * Deletes all given entities. Does nothing if {@code entities} is empty or {@code null}.
	 *
	 * @param entities the entities to delete
	 */
	public abstract void deleteAll(Collection<T> entities);

	/**
	 * Retrieves an entity by its primary key.
	 *
	 * @param id the primary key; must not be {@code null}
	 * @return the entity, or {@code null} if not found
	 */
	public abstract T findById(ID id);

	/**
	 * Returns all entities of type {@code T}.
	 *
	 * @return a list of all entities; never {@code null}
	 */
	public abstract List<T> findAll();

	/**
	 * Persists a new entity. Use {@link #update(Object)} to merge an existing one.
	 *
	 * @param entity the entity to persist; must not be {@code null}
	 */
	public abstract void save(T entity);

	/**
	 * Merges the state of the given entity into the current persistence context
	 * and returns the managed instance.
	 *
	 * @param entity the entity to merge; must not be {@code null}
	 * @return the managed entity after merge
	 */
	public abstract T update(T entity);

	/**
	 * Persists the entity and immediately flushes changes to the database.
	 *
	 * @param entity the entity to persist; must not be {@code null}
	 */
	public void saveAndFlush(T entity);

	/**
	 * Merges the entity and immediately flushes changes to the database.
	 *
	 * @param entity the entity to merge; must not be {@code null}
	 * @return the managed entity after merge and flush
	 */
	public T updateAndFlush(T entity);

	/**
	 * Deletes the entity and immediately flushes changes to the database.
	 *
	 * @param entity the entity to delete; must not be {@code null}
	 */
	public void deleteAndFlush(T entity);

	/**
	 * Persists all entities in the collection. Does nothing if the collection is empty.
	 *
	 * @param listT the entities to persist; must not be {@code null}
	 */
	public void saveAll(Collection<T> listT);

	/**
	 * Flushes all pending changes to the database.
	 */
	public void flush();

	/**
	 * Deletes the entity identified by the given primary key.
	 *
	 * @param id the primary key of the entity to delete; must not be {@code null}
	 */
	public void deleteById(ID id);

	/**
	 * Executes a dynamic JPQL query using the default {@code SELECT} statement
	 * generated by the annotation processor, applying all non-null parameters
	 * found in {@code queryParameter}.
	 *
	 * @param queryParameter filter parameters and optional pagination/ordering; must not be {@code null}
	 * @return list of matching entities; never {@code null}
	 */
	public List<T> findByFilter(QueryParameter<T, ID> queryParameter);

	/**
	 * Counts entities matching the given filter using the default {@code COUNT} query.
	 *
	 * @param queryParameter filter parameters; must not be {@code null}
	 * @return number of matching entities
	 */
	public Long countByFilter(QueryParameter<T, ID> queryParameter);

	/**
	 * Executes a dynamic JPQL query with a custom {@code SELECT} statement.
	 * Conditions and ordering from {@code queryParameter} are appended at runtime.
	 *
	 * @param queryParameter filter parameters; must not be {@code null}
	 * @param sql            custom JPQL SELECT fragment
	 * @return list of matching entities; never {@code null}
	 */
	public List<T> findByFilter(QueryParameter<T, ID> queryParameter, String sql);

	/**
	 * Counts entities using a custom JPQL {@code COUNT} statement and the given filter.
	 *
	 * @param queryParameter filter parameters; must not be {@code null}
	 * @param sql            custom JPQL COUNT fragment
	 * @return number of matching entities
	 */
	public Long countByFilter(QueryParameter<T, ID> queryParameter, String sql);

	/**
	 * Deletes entities matching the given filter.
	 * Internally resolves IDs first, then issues a bulk delete query.
	 *
	 * @param queryParameter filter parameters; must not be {@code null}
	 */
	public void deleteByFilter(QueryParameter<T, ID> queryParameter);

	/**
	 * Returns a single entity matching the filter using the default SELECT query.
	 * Returns {@code null} if no entity is found.
	 *
	 * @param queryParameter filter parameters; must not be {@code null}
	 * @return the matching entity, or {@code null}
	 */
	public T singleResultByFilter(QueryParameter<T, ID> queryParameter);

	/**
	 * Returns a single entity matching the filter using a custom SELECT query.
	 * Returns {@code null} if no entity is found.
	 *
	 * @param queryParameter filter parameters; must not be {@code null}
	 * @param select         custom JPQL SELECT fragment
	 * @return the matching entity, or {@code null}
	 */
	public T singleResultByFilter(QueryParameter<T, ID> queryParameter, String select);

	/**
	 * Executes the filter query and returns the results indexed by their primary key.
	 *
	 * @param queryParameter filter parameters; must not be {@code null}
	 * @return a map of {@code ID → entity}; never {@code null}
	 */
	public Map<ID, T> mapFindByFilter(QueryParameter<T, ID> queryParameter);

	/**
	 * Executes a custom SELECT query with the filter and returns results indexed by primary key.
	 *
	 * @param queryParameter filter parameters; must not be {@code null}
	 * @param sql            custom JPQL SELECT fragment
	 * @return a map of {@code ID → entity}; never {@code null}
	 */
	public Map<ID, T> mapFindByFilter(QueryParameter<T, ID> queryParameter, String sql);

	/**
	 * Executes the filter query and returns results indexed by a custom field value.
	 * Nested fields are supported using dot notation (e.g., {@code "address.city"}).
	 *
	 * @param <J>            the type of the custom key
	 * @param queryParameter filter parameters; must not be {@code null}
	 * @param classKey       the type of the custom key field
	 * @param key            field path (dot-notation) used as map key
	 * @return a map of {@code key → entity}; never {@code null}
	 */
	public <J> PersistenceMap<J, T> mapKeyFindByFilter(QueryParameter<T, ID> queryParameter, Class<J> classKey, String key);

	/**
	 * Executes a custom SELECT query and returns results indexed by a custom field value.
	 *
	 * @param <J>            the type of the custom key
	 * @param queryParameter filter parameters; must not be {@code null}
	 * @param sql            custom JPQL SELECT fragment
	 * @param classKey       the type of the custom key field
	 * @param key            field path (dot-notation) used as map key
	 * @return a map of {@code key → entity}; never {@code null}
	 */
	public <J> PersistenceMap<J, T> mapKeyFindByFilter(QueryParameter<T, ID> queryParameter, String sql, Class<J> classKey, String key);

	/**
	 * Executes the filter query and groups results in a list indexed by a custom field value.
	 *
	 * @param <J>            the type of the custom key
	 * @param queryParameter filter parameters; must not be {@code null}
	 * @param classKey       the type of the custom key field
	 * @param key            field path (dot-notation) used as map key
	 * @return a map of {@code key → List&lt;entity&gt;}; never {@code null}
	 */
	public <J> PersistenceMap<J, List<T>> mapKeyListFindByFilter(QueryParameter<T, ID> queryParameter, Class<J> classKey, String key);

	/**
	 * Executes a custom SELECT query and groups results in a list indexed by a custom field value.
	 *
	 * @param <J>            the type of the custom key
	 * @param queryParameter filter parameters; must not be {@code null}
	 * @param sql            custom JPQL SELECT fragment
	 * @param classKey       the type of the custom key field
	 * @param key            field path (dot-notation) used as map key
	 * @return a map of {@code key → List&lt;entity&gt;}; never {@code null}
	 */
	public <J> PersistenceMap<J, List<T>> mapKeyListFindByFilter(QueryParameter<T, ID> queryParameter, String sql, Class<J> classKey, String key);

	/**
	 * Executes a native SQL query and maps each row to a result object of type {@code K}
	 * using reflection-based mapping (column alias → field name).
	 *
	 * @param <K>            the result type
	 * @param queryParameter native query parameters including the result class; must not be {@code null}
	 * @param sql            native SQL SELECT statement
	 * @return list of mapped results; never {@code null}
	 */
	public <K> List<K> findByFilter(NativeQueryParameter<K, ID> queryParameter, String sql);

	/**
	 * Counts rows matching the native SQL query.
	 *
	 * @param <K>            the result type (not used in counting)
	 * @param queryParameter native query parameters; must not be {@code null}
	 * @param count          native SQL COUNT statement
	 * @return number of matching rows
	 */
	public <K> Long countByFilter(NativeQueryParameter<K, ID> queryParameter, String count);

	/**
	 * Returns a single result from a native SQL query, or {@code null} if not found.
	 * Throws a {@link RuntimeException} if more than one row is returned.
	 *
	 * @param <K>            the result type
	 * @param queryParameter native query parameters; must not be {@code null}
	 * @param sql            native SQL SELECT statement
	 * @return the single mapped result, or {@code null}
	 */
	public <K> K singleResultByFilter(NativeQueryParameter<K, ID> queryParameter, String sql);

	/**
	 * Executes a native SQL query and maps rows using a custom {@link JpaRowMapper}.
	 * Use this overload when the default reflection-based mapping is insufficient.
	 *
	 * @param <K>            the result type
	 * @param queryParameter native query parameters; must not be {@code null}
	 * @param sql            native SQL SELECT statement
	 * @param rowMapper      custom row-to-object mapper; may be {@code null} to use default mapping
	 * @return list of mapped results; never {@code null}
	 */
	public <K> List<K> findByFilter(NativeQueryParameter<K, ID> queryParameter, String sql, JpaRowMapper<K> rowMapper);

//	public T findSingleResultByFilter(QueryParameter<T, ID> queryParameter, StringBuilder select);
//
//	public Long countByFilter(QueryParameter<T, ID> queryParameter, StringBuilder count);
//
//	public List<T> findByFilter(QueryParameter<T, ID> queryParameter, StringBuilder select);

}
