spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/risto_db
    username: postgres
    password: Pa$$wd87!
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true 
        format_sql: true    
        ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true