server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/risto_db
    username: postgres
    password: Pa$$wd87!
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true 
        format_sql: true    
        ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    
 
 
bld:
  commons:
    exception:
      client:
        enable: true
        environment: DEV
        project: APP
        url: http://localhost:8080