/**
 * @author Francesco Baldi
 * @mail francesco.baldi1987@gmail.com
 * @class bld.commons.processor.annotations.ConditionBuilder.java
 */
package com.bld.commons.processor.annotations;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

import com.bld.commons.processor.OperationType;
import com.bld.commons.utils.types.UpperLowerType;

/**
 * Defines a single JPQL WHERE condition to be generated by the annotation processor.
 *
 * <p>Used as a nested annotation inside {@link QueryBuilder#conditions()}.
 * Each {@code @ConditionBuilder} declares the relationship between a JPQL entity
 * field, an {@link OperationType} (e.g., EQUALS, LIKE, IN), and the named
 * parameter that will carry the filter value at runtime.</p>
 *
 * <p>This annotation has {@link RetentionPolicy#CLASS} retention — it is read by
 * the annotation processor and is not retained at runtime.</p>
 *
 * <h3>Example</h3>
 * <pre>{@code
 * @QueryBuilder(
 *     conditions = {
 *         @ConditionBuilder(field = "e.name",     operation = OperationType.LIKE,
 *                           parameter = "name",   upperLower = UpperLowerType.LOWER),
 *         @ConditionBuilder(field = "e.active",   operation = OperationType.EQUALS,
 *                           parameter = "active"),
 *         @ConditionBuilder(field = "e.deletedAt",operation = OperationType.EQUALS,
 *                           parameter = "deletedAt", nullable = true)
 *     }
 * )
 * }</pre>
 *
 * @author Francesco Baldi
 * @see QueryBuilder
 * @see OperationType
 */
@Retention(RetentionPolicy.CLASS)
public @interface ConditionBuilder {

	/**
	 * The JPQL field expression to filter on (e.g., {@code "e.name"} or
	 * {@code "e.address.city"} for nested fields).
	 *
	 * @return the JPQL field path; must not be blank
	 */
	public String field();

	/**
	 * The comparison operation applied between {@link #field()} and the
	 * named parameter (e.g., {@code EQUALS}, {@code LIKE}, {@code IN}, {@code RANGE}).
	 *
	 * @return the operation type
	 */
	public OperationType operation();

	/**
	 * The name of the JPQL named parameter that carries the filter value at runtime
	 * (e.g., {@code "name"} → {@code :name}).
	 *
	 * @return the parameter name; must not be blank
	 */
	public String parameter();

	/**
	 * Optional case transformation applied to both the field and the parameter value
	 * before comparison. Defaults to {@code NONE} (no transformation).
	 *
	 * @return the case-transformation strategy
	 */
	public UpperLowerType upperLower() default UpperLowerType.NONE;

	/**
	 * When {@code true}, this condition is always appended to the WHERE clause
	 * even when the corresponding parameter value is {@code null}.
	 * Useful for IS-NULL conditions.
	 * Defaults to {@code false}.
	 *
	 * @return whether this is a nullable (always-included) condition
	 */
	public boolean nullable() default false;

}
