/**
 * @author Francesco Baldi
 * @mail francesco.baldi1987@gmail.com
 * @class bld.commons.processor.annotations.CustomConditionBuilder.java
 */
package com.bld.commons.processor.annotations;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

import com.bld.commons.processor.ConditionType;

/**
 * Defines a custom, hand-written condition fragment for use in either JPQL or
 * native SQL queries generated by the annotation processor.
 *
 * <p>Unlike {@link ConditionBuilder}, which generates the condition automatically
 * from a field path and an {@link com.bld.commons.processor.OperationType}, this
 * annotation lets you write the raw SQL/JPQL condition string directly.
 * Use it when the standard operation types are not expressive enough
 * (e.g., tuple comparisons, subqueries, vendor-specific syntax).</p>
 *
 * <p>It is used inside two distinct attributes of {@link QueryBuilder}:</p>
 * <ul>
 *   <li>{@link QueryBuilder#customConditions()} — for <strong>JPQL</strong> conditions.
 *       The condition is inserted into {@code MAP_CONDITIONS} (or
 *       {@code MAP_DELETE_CONDITIONS} when {@link #type()} is {@link ConditionType#DELETE})
 *       and is appended to the WHERE clause when the named parameter is non-null.</li>
 *   <li>{@link QueryBuilder#customNativeConditions()} — for <strong>native SQL</strong>
 *       conditions. The condition is placed in one or more named zone maps
 *       ({@code MAP_NATIVE_CONDITIONS}) identified by {@link #keys()}.
 *       At runtime each zone is injected into the SQL template via the
 *       {@code ${zoneName}} placeholder.</li>
 * </ul>
 *
 * <p><b>Example — custom JPQL condition</b></p>
 * <p>Use the entity alias and JPA field names (not column names).</p>
 * <pre>{@code
 * @QueryBuilder(
 *     customConditions = {
 *         @CustomConditionBuilder(
 *             condition = "and genere.idGenere in (:genereId)",
 *             parameter = "genereId"
 *             // type defaults to SELECT → MAP_CONDITIONS
 *         )
 *     }
 * )
 * }</pre>
 *
 * <p><b>Example — custom native SQL conditions with zones</b></p>
 * <pre>{@code
 * @QueryBuilder(
 *     customNativeConditions = {
 *         // Tuple comparison — not expressible with @ConditionBuilder
 *         @CustomConditionBuilder(
 *             condition  = "and (g.id_genere, pc.id_postazione_cucina) in (:genereTuple)",
 *             parameter  = "genereTuple",
 *             keys       = {"zone1", "zone2"}   // added to both zone maps
 *         ),
 *         @CustomConditionBuilder(
 *             condition  = "and g.id_genere in (:idGenere)",
 *             parameter  = "idGenere",
 *             keys       = {"zone1", "zone2"}
 *         )
 *     }
 * )
 * }</pre>
 *
 * <p>The generated {@code getMapNativeConditions()} will contain a map per key
 * (e.g., {@code "zone1"}, {@code "zone2"}), each holding the conditions assigned
 * to that zone. The native SQL template must expose matching placeholders:
 * {@code SELECT … FROM genere g ${zone1} …}</p>
 *
 * @author Francesco Baldi
 * @see QueryBuilder#customConditions()
 * @see QueryBuilder#customNativeConditions()
 * @see ConditionType
 */
@Retention(RetentionPolicy.CLASS)
public @interface CustomConditionBuilder {

	/**
	 * The named parameter key that activates this condition at runtime.
	 * The condition is appended to the WHERE clause only when a parameter
	 * with this name is present in the {@link com.bld.commons.reflection.model.QueryParameter}.
	 *
	 * @return the parameter name; must not be blank
	 */
	public String parameter();

	/**
	 * The raw JPQL or SQL condition fragment to inject (including the leading
	 * {@code AND} / {@code OR} keyword).
	 *
	 * <p>For native conditions the string is plain SQL; for JPQL conditions
	 * it must use JPQL syntax with named parameters (e.g., {@code :paramName}).</p>
	 *
	 * @return the condition fragment; must not be blank
	 */
	public String condition();

	/**
	 * Controls in which generated condition map this entry is placed.
	 * <ul>
	 *   <li>{@link ConditionType#SELECT} (default) — added to {@code MAP_CONDITIONS},
	 *       used for SELECT queries.</li>
	 *   <li>{@link ConditionType#DELETE} — added to {@code MAP_DELETE_CONDITIONS},
	 *       used for DELETE queries.</li>
	 * </ul>
	 * Applies only to {@link QueryBuilder#customConditions()} (JPQL).
	 *
	 * @return the condition type; defaults to {@link ConditionType#SELECT}
	 */
	public ConditionType type() default ConditionType.SELECT;

	/**
	 * One or more zone names this native condition belongs to.
	 * Each name corresponds to a key in the generated {@code MAP_NATIVE_CONDITIONS}
	 * map and to a {@code ${zoneName}} placeholder in the native SQL template.
	 *
	 * <p>The same condition can be registered in multiple zones by listing
	 * multiple keys. Defaults to {@code "default"} for JPQL custom conditions.</p>
	 *
	 * @return array of zone names; defaults to {@code {"default"}}
	 */
	public String[] keys() default "default";

}
